var apples = 0.75;
var bananas = 0.75;
var lettuce = 0.65;
var carrots = 1.50;
var bread = 1.99;
var butter = 3.50;
var beans = 0.85;
var soup = 1.50;
var cereal = 3.50;
var chicken = 3.29;
var eggs = 2;
var hamburger = 2.49;
var milk = 2.35;
var yogurt = 0.89;
var cheese = 2.99;
var iceCream = 3.50;
var rice = 1;
var tunaFish = 1.50;
var saladDressing = 1.60;
var peanutButter = 2.90;
var jam = 1.75;
var busFare = 1.25;
var ductTape = 3;
var maskingTape = 2;
var medicine = 5;
var shoes = 10;
var meal = (cereal + milk) + (hamburger * 2) + (lettuce + carrots + saladDressing + tunaFish);
console.log('meal total is ' + meal);
var myNeeds = busFare;
var girlNeeds = medicine;
var boyNeeds = maskingTape;
var needsInTotal = myNeeds + girlNeeds + boyNeeds;
console.log('all needs equal up to ' + needsInTotal);
var total = meal + needsInTotal;
console.log('the total of everything we need is ' + total);
